name: fraud_detection
channels:
- defaults
- conda-forge
dependencies:
- ipykernel>=4.6.1
- jupyter>=1.0.0
- numpy>=1.13.3
- pandas>=0.23.4
- python=2.7
- pip:
  - matplotlib
  - scikit-learn
  - keras==2.1.5
  - tensorflow==1.5.0
  - lifelines
